Task_1_1_1
MlronGaskov/OOP pull request #2
Opened 2024-09-06 18:30 UTC by MlronGaskov

2024-09-07 05:53 UTC, galinabykova requested changes
тык

2024-09-07 14:38 UTC, galinabykova requested changes
нужно добавить скрипт из условия задания, исправить замечания ревьюдога и пару мелких правок. Решение очень хорошее)

2024-09-07 14:38 UTC, galinabykova commented on Task_1_1_1/src/test/java/ru/nsu/gaskov/HeapSortTest.java
> +        long[] array = {5L, 3L, 9L, 1L, 4L};
мне кажется, на лонг можно было взять большое число, которые не влазит в инт, чисто проверить, что по ошибке нигде случайно в int не сохранил и не случилось переполнения. Но это так, придирка, мне же надо что-то написать

2024-09-07 14:38 UTC, galinabykova commented on Task_1_1_1/src/test/java/ru/nsu/gaskov/HeapSortTest.java
> +            if (size == 5000000) {
у тебя два раза константа повторяется. лучше сделать переменную, чтобы не получилось ситуации, когда случайно только в одном месте поменяли

2024-09-07 14:38 UTC, galinabykova commented on Task_1_1_1/src/test/java/ru/nsu/gaskov/HeapSortTest.java
это менять не надо, просто описываю ощущение. Сейчас тесты очень сложно читать. В первую очередь, это связано с тем, что много однотипного кода, конечно, но также у тебя в них как будто нет системы. Ты сначала один вид теста начал писать для каждого типа данных, а потом для каждого типа данных писал разные тесты. Из-за этого очень сложно понять, что протестировано, а что ещё нет

Остальным ребятам я советовала разделять тесты, но поскольку у тебя по сути декартово произведение вид тест * тип данных, я бы советовала их наоборот объединить и использовать тут табличные тесты с помощью параметризованных. Выглядеть это может, например, вот так

```java
public class Main {
    public static int[] lya(int[] a) {
        return a;
    }
}
```

```java
    @DisplayName("Integer Test")
    @ParameterizedTest(name = "{0}")
    @CsvSource({
            "simpleTest, 1 1 1",
            "oneElemTest, 1"})
    void LyaIntTest(String name, String stringArray){
        var array = Arrays.stream(((String) stringArray).split(" ")).mapToInt(Integer::parseInt).toArray();
        assertEquals(array, Main.lya(array));
    }
```

Мне кажется, так выглядит более читаемо
Переделывать я тебя не прошу, слишком муторно, но подумала, что тебе может быть интересно, что так можно сделать

2024-09-08 13:31 UTC, MlronGaskov commented
добавил файл build.sh, исправил ошибки по codestyle

2024-09-08 14:51 UTC, galinabykova approved these changes

2024-09-08 16:10 UTC, merged