Task_1_1_2
MlronGaskov/OOP pull request #4
Opened 2024-09-15 14:42 UTC by MlronGaskov

2024-09-15 15:26 UTC, MlronGaskov commented
Я захотел сделать немного более сложный блэкджек. Игроков может быть несколько, возможны действия insure, split, double. Можно делать ставки. Проект рабочий, можно поиграть запустив GameUI.main(), но сам GameUI и Game хочу переделать так что по возможности их лучше не смотреть:)

2024-09-16 04:16 UTC, galinabykova requested changes
мягкий засчитан, Game и GameUI не смотрела

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/input/StandardDecksNumberCondition.java
PlayerNumberCondition, StandartDecksNumbersCondition, BetCondition имеют практически идентичный код. Мне кажется, в такой ситуации было бы уместнее делать не отдельные классы условия, а общий класс для Integer, который принимал бы в конструкторе границы, в которых принимает ответ (например 0, 8 для StandardDecksNumberCondition). Помимо сокращения дублирующего кода, это позволило бы в классе Game видеть границы ввода

Впрочем, если считаешь, что отдельные классы уместны, можешь сделать им общего предка или вынести дублирующий код куда-нибудь. Обязательно - избавиться от повторяющегося кода. Дублирующийся код затрудняет поддержку кода - если будет найдена ошибка в одном месте, надо будет её везде не забыть поменять

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/input/AnswerCondition.java
> +        String[] validAnswers = new String[] {"YES", "Y", "NO", "N"};
final

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/input/AnswerCondition.java
> +        if (!isValid(input)) {
если я правильно поняла, вызов isValid нужен, чтобы избежать дублирования
```java
        if (input == null || input.isEmpty()) {
            return false;
        }
```
Если это так, немножко не очевидно, мне понадобилась минутка, чтобы понять - а зачем?
Если хочешь избежать дублирования, можно сделать общий метод, принимающий строку с допустимыми паттернами

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/input/AnswerCondition.java
> +        String[] validAnswers = new String[] {"YES", "Y"};
final

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/input/InputValidator.java
> +public class InputValidator {
не уверена, что это прям Валидатор, так как он помимо проверки данных, выводит поясняющую строчку и считывает строку с ввода, но, наверно, и так норм

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/Game.java
> +    public void countMoney(int[] roundOutcomes) {
кажется, предполагается, что этот метод будет вызван только в какой-то конкретный момент игры. Если так, нужно прописать это в документации.

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/gaskov/input/AnswerConditionTest.java
> +    public void validYesAnswersTest() {
когда у тебя много независящих друг от друга тестовых ситуаций в одном тесте, тебе может быть интересно протестировать их все, а не только до первого падения. Знание, что падает не один тест, а больше - важная дополнительная информация, которая может помочь быстрее отладить код. А ещё ты сможешь увидеть все баги, а только один.

Это особенно важно, если запускаешь ты где-то удалённо и быстро перезапустить нет возможности. Чтобы запускались сразу все тесты нужно использовать assertAll

https://www.baeldung.com/junit5-assertall-vs-multiple-assertions
https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertAll-org.junit.jupiter.api.function.Executable...-

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/Hand.java
> +            if (getCards1Value() >= 21) {
магическая константа

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/Hand.java
> +    public List<Card> getCards1() {
список является ссылочным типом, соответственно здесь ты фактически даёшь доступ к  своему полю Card, позволяя, например, добавлять в него новые карты. Так иногда делают, когда по другому не получается, но такой геттер - повод посмотреть, а не смешиваешь ли ты детали реализации с поведением. Также, если объект небольшой, вместо передачи по ссылке его можно копировать, если предполагается, что объект не должны менять.

Тебя тут я предлагаю посмотреть использование этого метода в других классах и проверить, а нужен ли тебе именно такой метод. Мне кажется, можно было перенести подсчёт очков (для которого судя по всему и нужен этот геттер) в этот класс, но ты можешь со мной не согласиться

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/OutcomeCalculator.java
> +        if (pileValue > 21) {
магические константы

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/OutcomeCalculator.java
> +        } else if (dealerValue > 21) {
кажется, тут else не надо

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/OutcomeCalculator.java
> +        } else if (dealerValue > 21) {
потому что в теле условия return

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/Round.java
> +    Deck deck;
навесь на поля модификаторы. Когда я читаю твой код и вижу отсутствие private, я воспринимаю это как "ага, это поле может менять в другом месте, надо сходить посмотреть, где, вдруг его где-то вне класса меняют". А когда я вижу private, то понимаю, что можно ограничить анализ этого класса только этим файлом

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/OutcomeCalculator.java
> +        } else if (dealerValue > 21) {
и в других местах кода аналогичную ошибку надо исправить

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/card/Card.java
> +    public boolean equals(Object object) {
https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-
посмотри последнюю строчку документации этого метода

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/deck/LargeDeck.java
> +    public void collect() {
везде, где ты переопределяешь метод нужно использовать аннотацию Override. Она гарантирует, что ты действительно переопределяешь, а не перегружаешь метод или не создаёшь новый, если опечатаешься

2024-09-16 04:16 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/player/Player.java
> +public interface Player {
а зачем ты тут делаешь дефолтные реализации методов?

2024-09-22 06:25 UTC, galinabykova requested changes

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/gaskov/ui/GameUserInterfaceTest.java
> +    public void testGameEnd() {
в этом тесте ничего не проверяется

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Game.java
> +    public final Player[] players;
нужно избавиться от полей с публичным доступом, так как поле это деталь реализации, а реализация класса чаще меняется, чем поведение, в процессе поддержки кода. Когда я смотрю код также удобнее, когда поля видны только внутри класса - не надо бегать по всему коду, чтобы понять поведение, можно изучать отдельные классы

Если тебе доступ к этому полю нужно чисто для тестов, можно сделать package-private доступ, но и в такой ситуации лучше подумать, а нельзя ли иначе проверить корректность

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Hand.java
> +            if (getCards1Value() >= 21) {
магическая константа. Нужно дать имя и везде использовать её. Это поможет быстро поменять конечное значение и сделает код более читаемым

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Hand.java
> +    public List<Card> getCards1() {
продублирую прошлый комментарий
список является ссылочным типом, соответственно здесь ты фактически даёшь доступ к своему полю Card, позволяя, например, добавлять в него новые карты. Так иногда делают, когда по другому не получается, но такой геттер - повод посмотреть, а не смешиваешь ли ты детали реализации с поведением. Также, если объект небольшой, вместо передачи по ссылке его можно копировать, если предполагается, что объект не должны менять.

Тебя тут я предлагаю посмотреть использование этого метода в других классах и проверить, а нужен ли тебе именно такой метод. Мне кажется, можно было перенести подсчёт очков (для которого судя по всему и нужен этот геттер) в этот класс, но ты можешь со мной не согласиться

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Game.java
> +    public final Player[] players;
а, я криво сформулировала в прошлый раз, прости. Имелось ввиду, расставить минимально необходимые модификаторы. Везде, где возможно, сделать доступ private. Где невозможно, нужно обосновать почему. Точно не должно быть такого, чтобы к полям получали доступ другие классы, за исключением тестов. В тестах тоже нежелательно, но обсуждаемо

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Game.java
> +    public final Player[] players;
ну и если доступ только в тестах, тогда нужен package-private, как и было ранее

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/LargeDeck.java
> +    public void collect() {
override?

2024-09-22 06:25 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/gaskov/ui/GameUserInterfaceTest.java
> +    public void testGameEnd() {
проверь, что в выводе очки, например, верные или выигрывает тот, кто должен, или ещё что-нибудь

2024-09-22 10:22 UTC, MlronGaskov commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Hand.java
> +    public List<Card> getCards1() {
Так я вроде же создаю новый список, а Card - это record. Вроде безопасно должно быть. А этот геттер я использую еще и для отображения, так что от него не избавиться

2024-09-22 10:22 UTC, MlronGaskov commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Hand.java
> +            if (getCards1Value() >= 21) {
исправил

2024-09-22 10:22 UTC, MlronGaskov commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/LargeDeck.java
> +    public void collect() {
исправил

2024-09-22 11:07 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/gaskov/core/Hand.java
> +    public List<Card> getCards1() {
А, точно, я просмотрела

2024-09-22 13:39 UTC, galinabykova approved these changes

2024-09-22 14:37 UTC, merged