Task_1_2_1
MlronGaskov/OOP pull request #6
Opened 2024-10-13 13:14 UTC by MlronGaskov

2024-10-13 13:15 UTC, MlronGaskov commented
Вроде все сделал. Осталось добавить тесты и джавадоки

2024-10-13 15:48 UTC, galinabykova requested changes
мягкий засчитан, жду тесты по остальным видам графов

2024-10-13 15:48 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/EdgeReader.java
> +public abstract class EdgeReader<V extends Vertex, E extends OrientedEdge<V>> {
а почему ты решил делать тут абстрактный класс, а не интерфейс?

2024-10-13 15:48 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/AdjacencyListGraph.java
> +        return vertices;
тут ссылка на поле, мне это не нравится, хотя и копировать каждый раз не хочется. Предлагаю прописать в документации, что менять список по этой ссылке нельзя. Ещё можно дополнительно использовать https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Collection.html#unmodview, мне не очень нравится, как эта штука устроена в java (тут мы где-то на грани нарушения принципа Лисков), но сама идея интересная (в C++ есть, например, string_view, они как будто лучше выглядят)

2024-10-13 15:48 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/AdjacencyListGraph.java
> +        Scanner scanner = new Scanner(new File(filename));
небольшой теоретический вопрос. Что произойдёт, если файл не будет найден? Когда он будет закрыт и будет ли?

2024-10-13 15:48 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/AdjacencyListGraph.java
> +    public boolean equals(Object object) {
можно было в интерфейсе графа сделать дефолтную реализацию этого метода. Тогда была бы одна реализация, но, возможно, менее эффективная (хотя у меня ощущение, что у тебя equals очень похожи, так что вряд ли)

2024-10-13 15:48 UTC, galinabykova commented on Task_1_2_1/src/test/java/ru/nsu/gaskov/graph/TopologicalSortTest.java
тут от дублирующего кода надо избавиться. Можешь разобраться с параметризованными тестами, про которые я писала, или просто в общий метод вынести часть дублирующего кода, тоже норм будет

2024-10-20 13:05 UTC, MlronGaskov commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/EdgeReader.java
> +public abstract class EdgeReader<V extends Vertex, E extends OrientedEdge<V>> {
переделал в интерфейс

2024-10-20 13:05 UTC, MlronGaskov commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/AdjacencyListGraph.java
> +        return vertices;
ок

2024-10-20 13:05 UTC, MlronGaskov commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/AdjacencyListGraph.java
> +        Scanner scanner = new Scanner(new File(filename));
теперь точно будет закрыт

2024-10-20 13:05 UTC, MlronGaskov commented on Task_1_2_1/src/test/java/ru/nsu/gaskov/graph/TopologicalSortTest.java
исправил

2024-10-20 13:20 UTC, MlronGaskov commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/AdjacencyListGraph.java
> +    public boolean equals(Object object) {
Classes with implementations always win over default methods, so having a default hashCode or equals can never be invoked and therefore is forbidden.
https://stackoverflow.com/questions/28019242/java-8-default-method-interface-override-object-equals-method

2024-10-20 15:25 UTC, galinabykova commented on Task_1_2_1/src/main/java/ru/nsu/gaskov/graph/AdjacencyListGraph.java
> +    public boolean equals(Object object) {
о, не подумала об этом, круто)

2024-10-20 15:26 UTC, galinabykova approved these changes

2024-10-20 15:50 UTC, merged