Task_1_2_2
MlronGaskov/OOP pull request #7
Opened 2024-10-27 12:06 UTC by MlronGaskov

2024-10-27 12:07 UTC, MlronGaskov commented
остались джавадоки и чекстайл

2024-10-27 16:13 UTC, galinabykova requested changes
мягкий засчитан, но я не смогла быстро нагуглить асимптотику алгоритма твоей хэш-таблицы, пришли мне, пожалуйста, пруфы, что у тебя амортизированная константа (какую-нибудь ссылку с доказательством)

UPD. мне прислал другой студент с таким же алгоритмом, так что просьба не актуальна)

2024-10-27 16:13 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/Entry.java
> +        return key.equals(((Entry<K, V>) obj).key)
мне кажется, тут можно не уточнять типы K и V (использовать <?,?>). Если тип будет неверный, equals ключа и значения должны вернуть ложь

2024-10-27 16:13 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +        table = new Entry[initCapacity];
лучше писать Entry<K, V>. Ты используешь много @SuppressWarnings("unchecked"), нужно, чтобы каждое использование было осмысленным. Постарайся в каждом случае или избавиться от @SuppressWarnings("unchecked"), или обосновать, почему без него нельзя

2024-10-27 16:13 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +        table = new Entry[2 * oldTable.length];
укажи тип <K, V>

2024-10-27 16:13 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +    public boolean equals(HashTable<K, V> other) {
мне кажется, лучше всё-таки переопределить метод из Object, а не перегружать. Потому что это стандартный способ и я уверена, что при полном переопределении не вылезет ничего странного. В твоей версии я, например, подозреваю, что могут быть странности при попытке сравнить хэш-таблицы разных типов из-за стирания типов. Но можешь попробовать обосновать, почему твой вариант с перегрузкой тоже норм

2024-10-27 16:13 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/Entry.java
> +    public boolean equals(Object obj) {
hashcode

2024-10-27 16:20 UTC, galinabykova commented
> мягкий засчитан, но я не смогла быстро нагуглить асимптотику алгоритма твоей хэш-таблицы, пришли мне, пожалуйста, пруфы, что у тебя амортизированная константа (какую-нибудь ссылку с доказательством)

UPD. мне прислал другой студент с таким же алгоритмом, так что просьба не актуальна)

2024-10-28 04:42 UTC, MlronGaskov commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/Entry.java
> +        return key.equals(((Entry<K, V>) obj).key)
исправил

2024-10-28 04:44 UTC, MlronGaskov commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +        table = new Entry[initCapacity];
Generic array creation not allowed пишет

2024-10-28 04:44 UTC, MlronGaskov commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +        table = new Entry[2 * oldTable.length];
Generic array creation not allowed

2024-10-28 05:08 UTC, MlronGaskov commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/Entry.java
> +    public boolean equals(Object obj) {
добавил

2024-10-28 05:09 UTC, MlronGaskov commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +    public boolean equals(HashTable<K, V> other) {
переделал

2024-10-28 05:47 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +        table = new Entry[initCapacity];
аааа, у тебя массивы, поэтому так
на всякий случай - https://stackoverflow.com/questions/9542076/array-of-parameterized-types тут про массивы и дженерики
предлагаю использовать ArrayList вместо массивов. По асимптотике будет также, но с дженериками они лучше работают, мне кажется, с ними получится снизить количество @SuppressWarnings("unchecked")

2024-10-31 05:43 UTC, galinabykova requested changes

2024-10-31 05:43 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashtable/HashTable.java
> +    private int modCount = 0;
мне кажется, лучше сделать long, потому что  int может достаточно быстро переполниться и могут возникнуть проблемы

2024-10-31 05:43 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +        table = new Entry[initCapacity];
@MlronGaskov

2024-11-02 09:40 UTC, MlronGaskov commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashTable/HashTable.java
> +        table = new Entry[initCapacity];
поменял

2024-11-02 09:40 UTC, MlronGaskov commented on Task_1_2_2/src/main/java/ru/nsu/gaskov/hashtable/HashTable.java
> +    private int modCount = 0;
исправил

2024-11-02 15:54 UTC, galinabykova approved these changes

2024-11-03 06:23 UTC, merged