Task_1_3_1
MlronGaskov/OOP pull request #8
Opened 2024-11-09 05:51 UTC by MlronGaskov

2024-11-09 05:54 UTC, MlronGaskov commented
Решил сделать итератор по индексам, потому что все индексы могут не поместиться в оперативную память

2024-11-09 15:34 UTC, galinabykova requested changes
я обычно принимаю решение, в котором список может храниться в памяти, но здорово, что ты об этом подумал, очень хорошее решение,  было приятно читать, мягкий засчитан)

2024-11-09 15:34 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/gaskov/text/search/KmpSubstringSearcher.java
> +        private Long positionInText = 0L;
а почему Long, а не long, что-то не поняла

2024-11-09 15:34 UTC, galinabykova commented on Task_1_3_1/src/main/java/ru/nsu/gaskov/text/search/KmpSubstringSearcher.java
> +                throw new RuntimeException(e);
Оооо, ты тут столкнулся с штукой, из-за которой явное прописывание исключений в сигнатуре иногда хейтят. Хорошее решение, но предлагаю сделать собственного наследника RuntimeException (чтобы его можно было специализировано поймать) и прописать в документации, что ты бросаешь это исключение (потому что пользователь всё-таки это никак не ожидает)

2024-11-09 15:34 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/gaskov/text/search/KmpSubstringSearcherTest.java
Обычно тестовые файлы не генерируют в тесте, а сохраняют как ресурсы. Ситуация с большим файлом уникальная - ты просто не сможешь загрузить его на гитхаб, поэтому его генерим.
В этой лабе или лабе с графами нужно познакомиться с ресурсами (я прошу в этой, потому что она меньше). Поэтому, пожалуйста, добавь тест, в котором файл будет прочитан как ресурс

2024-11-11 07:37 UTC, MlronGaskov commented on Task_1_3_1/src/main/java/ru/nsu/gaskov/text/search/KmpSubstringSearcher.java
> +        private Long positionInText = 0L;
тут не надо Long:) исправил

2024-11-11 08:11 UTC, MlronGaskov commented on Task_1_3_1/src/test/java/ru/nsu/gaskov/text/search/KmpSubstringSearcherTest.java
добавил

2024-11-11 08:12 UTC, MlronGaskov commented on Task_1_3_1/src/main/java/ru/nsu/gaskov/text/search/KmpSubstringSearcher.java
> +                throw new RuntimeException(e);
сделал

2024-11-11 08:22 UTC, MlronGaskov commented
замечания исправил

2024-11-11 08:37 UTC, galinabykova requested changes

2024-11-11 08:37 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/gaskov/text/search/KmpSubstringSearcherTest.java
> +        Path filePath = Paths.get("src/test/resources/testfile.txt");
ресурсы читают немного по другому. Есть специальные методы, посмотри методы тут (чисто методы, хорошего источника я не нашла по этой теме)
https://sky.pro/wiki/java/poluchenie-puti-k-resursu-v-jar-fayle-java-resheniya-i-oshibki/
https://stackoverflow.com/questions/3861989/preferred-way-of-loading-resources-in-java
в статическом методе можно написать НазваниеКласса.class вместо getClass

Лучше использовать их, потому что сейчас ты всё ещё привязываешься к месту, где хранится код. А ресурсы по умолчанию сохраняются в сборке рядом с класс-файлами. Можешь ради интереса полазить по сборке, которая у тебя создаётся, чисто посмотреть, куда у тебя будет скопирован testfile

2024-11-11 08:37 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/gaskov/text/search/KmpSubstringSearcherTest.java
> +        Path filePath = Paths.get("src/test/resources/testfile.txt");
то есть надо прочитать ресурс как ресурс

2024-11-11 10:00 UTC, MlronGaskov commented on Task_1_3_1/src/test/java/ru/nsu/gaskov/text/search/KmpSubstringSearcherTest.java
> +        Path filePath = Paths.get("src/test/resources/testfile.txt");
теперь читаю через getResourceAsStream

2024-11-12 03:37 UTC, galinabykova approved these changes

2024-11-12 03:37 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/gaskov/text/search/KmpSubstringSearcherTest.java
> +        String text = "sample text for testing";
здорово, что ты сделал тесты через строки, это хорошее решение тут

2024-11-12 03:37 UTC, galinabykova commented on Task_1_3_1/src/test/java/ru/nsu/gaskov/text/search/KmpSubstringSearcherTest.java
> +        try (BufferedWriter writer = Files.newBufferedWriter(tempFile)) {
хотя по умолчанию используется кодировка UTF-8, мне кажется, хорошая идея указывать её явно, чтобы читающий код это не упустил. Исправлять не надо, просто мысль

2024-11-13 02:49 UTC, merged