Task_1_4_1
MlronGaskov/OOP pull request #9
Opened 2024-11-21 14:08 UTC by MlronGaskov

2024-11-22 06:22 UTC, galinabykova requested changes

2024-11-22 06:22 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/gaskov/gradebook/GradeBook.java
> +        boolean noSatisfactoryGrades = grades.stream().noneMatch(grade -> grade.getScore() == 3);
а двойка тут не может быть?

2024-11-22 06:22 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/gaskov/gradebook/GradeBook.java
> +        );
перепиши без forEach, но со StreamAPI (чтобы потренироваться в использовании StreamAPI)
возможно, тебе понадобится https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toMap-java.util.function.Function-java.util.function.Function-java.util.function.BinaryOperator-

2024-11-22 06:22 UTC, galinabykova commented on Task_1_4_1/src/test/java/ru/nsu/gaskov/gradebook/GradeBookTest.java
> +    void testCanGetRedDiploma() {
для красного диплома много условий. Сделай отдельные тесты для проверки каждого из этих условий

2024-11-23 16:21 UTC, MlronGaskov commented on Task_1_4_1/src/main/java/ru/nsu/gaskov/gradebook/GradeBook.java
> +        boolean noSatisfactoryGrades = grades.stream().noneMatch(grade -> grade.getScore() == 3);
Вроде не может, итоговая два ведь не может быть

2024-11-23 16:22 UTC, MlronGaskov commented on Task_1_4_1/src/main/java/ru/nsu/gaskov/gradebook/GradeBook.java
> +        boolean noSatisfactoryGrades = grades.stream().noneMatch(grade -> grade.getScore() == 3);
но исправил на всякий случай

2024-11-23 16:50 UTC, MlronGaskov commented on Task_1_4_1/src/test/java/ru/nsu/gaskov/gradebook/GradeBookTest.java
> +    void testCanGetRedDiploma() {
добавил тесты

2024-11-23 16:50 UTC, MlronGaskov commented on Task_1_4_1/src/main/java/ru/nsu/gaskov/gradebook/GradeBook.java
> +        );
переписал

2024-11-24 06:25 UTC, galinabykova approved these changes

2024-11-24 07:36 UTC, merged